Dev
esqLABS/ESQapp pull request #51
Opened 2024-05-08 09:07 UTC by AKostiv8

2024-05-08 09:09 UTC, PavelBal commented on DESCRIPTION
> +Authors@R: person('Felix', 'MIL', email = 'felix.mil@esqlabs.com', role = c('cre', 'aut'))
@AKostiv8 Please add yourself to the list of authors.

2024-05-13 08:17 UTC, PavelBal requested changes
The PR should not contain any commented code. If there are parts you are still working on, then either finish them before merging, or remove and work on them in a separate branch/PR.

2024-05-13 08:17 UTC, PavelBal commented on R/app_ui.R
> +    # tags$link(rel = "stylesheet", type = "text/css", href = "style.css"),
Make sure that no commented code is left in the PR.

2024-05-13 08:17 UTC, PavelBal commented on R/mod_edit_table.R
> +  # datamods::edit_data_ui(ns("edit_df"))
Commented code

2024-05-13 08:17 UTC, PavelBal commented on R/mod_edit_table.R
> +      # browser()
;)

2024-05-13 13:08 UTC, Felixmil requested changes
- [x] Remove commented code
- [x] Add entries in NEWS describing what is implemented

For next PRs: keep it related to one main change or one topic related implementations.

General recommendations: https://dev.open-systems-pharmacology.org/r-development-resources/collaboration_guide#rules

2024-05-31 12:38 UTC, Felixmil commented
Please, add `Remotes` entries in the `DESCRIPTION` file for `{esqlabs.handsontable}` and `{esqlabs.ui}`

2024-06-04 08:20 UTC, Felixmil commented on R/mod_import.R
> +    return(projectConfiguration)
Also, this value could easily be added to the reactive list `r` in the observer at line 56:
```r
observeEvent(projectConfiguration(), {

   r$configurationPath <- projectConfiguration()$projectConfigurationFilePath

   for (config_file in names(r$data)) {
   ...

2024-07-17 13:12 UTC, Felixmil commented on NEWS.md
> +## Version 0.0.0.1 (2024-05-26)
```suggestion
## Version 0.0.0.9000
```

2024-07-17 13:19 UTC, Felixmil requested changes

2024-07-17 14:24 UTC, Felixmil requested changes

2024-07-18 07:32 UTC, Felixmil approved these changes
Just one line to remove then ok to merge

2024-07-18 07:32 UTC, Felixmil commented on README.Rmd
> +Note: For projects created for version 3 of `esqlabsR` package, install [`esqlabsRLegacy`](https://github.com/esqLABS/esqlabsRLegacy).
this is not applicable here

2024-07-18 09:42 UTC, PavelBal approved these changes

2024-07-18 10:40 UTC, merged